### ISSUE TITLE
Add test coverage reports

### ISSUE THREAD

**Issue by pbardea** [graphflow/graphflow#9]
We want to be able to see the current code coverage of graphflow. To achieve this we need to add JaCoCo and Coveralls.

@sachdevs and I will tackle this.

**Comment by semihsalihoglu-uw** [comment]
LGTM on my side. I am guessing  Amine and Siddhartha will be fine too but just have a quick discussion with them too.

**Comment by queryproc** [comment]
@pbardea and @sachdevs added the coverall tool.
Both the test coverage % and the build status badges were added to the REAME file.
